repos:
-   repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
    - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args: ["--profile", "black"]
# -   repo: https://github.com/econchick/interrogate
#     rev: 1.4.0  
#     hooks:
#     - id: interrogate
#       args: [-vv, -i, --fail-under=80]
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0 # Use the ref you want to point at
  hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: end-of-file-fixer
      - id: detect-private-key
